import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/Hero';
import Features from '../components/Features';
import Footer from '../components/Footer';
import Contact from '../components/Contact';
import React from 'react';
import {
  WifiIcon,
  AcademicCapIcon,
  GlobeAltIcon,
  BookOpenIcon,
  SparklesIcon,
} from '@heroicons/react/24/outline';
// interface MasjidDatas {
//   name: string;
//   desc: string;
//   primaryColor: string;
//   secondaryColor: string;
//   kegiatan: {
//     name:
//       | boolean
//       | React.ReactElement<any, string | React.JSXElementConstructor<any>>
//       | React.Key
//       | React.ReactFragment
//       | null
//       | undefined;
//     icon: React.FunctionComponent;
//     description:
//       | string
//       | number
//       | boolean
//       | React.ReactElement<any, string | React.JSXElementConstructor<any>>
//       | React.ReactFragment
//       | React.ReactPortal
//       | null
//       | undefined;
//   }[];
// }

const masjidDatas = {
  name: 'Skembet',
  desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maxime dicta inventore esse hic. Recusandae id labore officiis tempora in alias!',
  logo: false,
  primaryColor: '#c7c7c7',
  secondaryColor: '#2e2e2e',
  // kegiatan: [
  //   {
  //     name: "Ta'lim Pekanan",
  //     description:
  //       'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
  //     icon: AcademicCapIcon,
  //   },
  //   {
  //     name: 'Tahfidz Weekends',
  //     description:
  //       'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
  //     icon: BookOpenIcon,
  //   },
  //   {
  //     name: 'Cafe Gratis',
  //     description:
  //       'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
  //     icon: WifiIcon,
  //   },
  //   {
  //     name: 'Jumat Berkah',
  //     description:
  //       'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.',
  //     icon: AcademicCapIcon,
  //   },
  // ],
};

export const masjidContext = React.createContext(masjidDatas);

const Home: NextPage = () => {
  return (
    <div className="relative min-h-screen pb-32 bg-white">
      <Head>
        <title>Homepage</title>
        <meta name="descrption" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <masjidContext.Provider value={masjidDatas}>
        <Hero />
        <Features />
        {/* <Contact /> */}
        <Footer />
      </masjidContext.Provider>
    </div>
  );
};

export default Home;
